### ISSUE TITLE
Weird vertical columns

### ISSUE THREAD

**Issue by zgredinzyyy** [AGH-Wstep-do-Informatyki-2023-2024/AlgebraMiodzio#8]
![image](https://github.com/AGH-Wstep-do-Informatyki-2023-2024/AlgebraMiodzio/assets/25299505/6ebb926d-761e-4b53-875b-631c4f81cc38)

This shouldn't be happening we need to fix this somehow

**Comment by mateuszweglewski** [comment]
We need to shake it off

**Comment by zgredinzyyy** [comment]
@0Qrb fixed it in newest branch :>
